In [3]:
import torch
import numpy as np
import os
import sys
import time

In [4]:
a = torch.arange(6).reshape(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [5]:
torch.einsum('ij->ji', [a])

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [7]:
# sum
torch.einsum('ij->', [a])

tensor(15)

In [8]:
# col sum
torch.einsum('ij->j', [a])

tensor([3, 5, 7])

In [9]:
# row sum
torch.einsum('ij->i', [a])

tensor([ 3, 12])

In [15]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
print(a)
print(b)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [16]:
# ensure that shape fits
assert a.shape[1] == b.shape[0]
torch.einsum('ik,kj->ij', [a, b])

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])